version: "3.7"

services:

  shoutrrr_alertmanager_bridge:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: shoutrrr_alertmanager_bridge
    #image: ghcr.io/rodriciru/shoutrrr_alertmanager_bridge:main
    volumes:
      - ./s_a_b/:/etc/s_a_b/
    ports:
      - 30000:30000
      #environment: 
      #- SERVICES_CONFIG=/etc/s_a_b/services.json
      #- TEMPLATES_PATH=/etc/s_a_b/templates/

  gotify:
    container_name: gotify
    image: gotify/server:latest
    ports:
      - 8080:80
    volumes:
      - ./gotify:/app/data
      - ./gotify/config.yml:/etc/gotify/config.yml
    restart: always

  alertmanager:
    container_name: alertmanager
    image: quay.io/prometheus/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager/:/etc/alertmanager/
      # - ./alertmanager/storage/:/alertmanager/
    restart: always
    command:
      - "--config.file=/etc/alertmanager/config.yml"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus/:/prometheus
    ports:
      - 9090:9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    restart: always
